### PR TITLE
Result page

### PR DESCRIPTION
**Pull request by vrinda-mahajan**
Added the result page to the quiz app. Please review my PR.

Preview: https://nostalgic-perlman-e6f11e.netlify.app/pages/resultpage/result

### CODE REVIEW

**Review by Maianki — APPROVED** [review]
Looks good to merge.

**Review by vrx29 — APPROVED** [review]
Nice UI and code is clean as well. Good to merge.

**Review by MayankKumar10 — APPROVED** [review]
Looks Good you can merge it.

**Review by anik31 — APPROVED** [review]
Everything looks great. Just one suggestion to change the bg-color of options to some lighter shade so that the option-correct can be easily distinguished.

**Review by VLeads — APPROVED** [review]
All are good. But I noticed in UI that you missed to add cursor pointer to button. You can add that.

**Pull request merged**
